[illustrations]
ill_music = "Illustration/Music - Celebrate"
ill_travel = "Illustration/Travels"
ill_ecommerce = "Illustration/E-commerce"
ill_family = "Illustration/Family"

[xml-icons]
fav_filled = "fav-filled"
