[config]
workspace = true

# This packages only reuses other packages 
# and do not have their own logic
exclude = [
    "figx",
    "command_clean",
    "command_explain",
    "command_fetch",
    "command_import",
    "command_info",
    "command_query",
]

exclude-files = [
    # This files is always for error impl boilerplate
    "**/error.rs",
    # Cannot test ureq's network requests now
    "crates/lib/figma-fluent/src/data.rs",
    # Just plain structs of parser api, no need to cover
    "crates/phase/loading/src/api.rs",
]

out = ["Html", "Xml"]
