[remotes.icons]
file_key = "Q5KZlwws4rsDW8grU91xLR"
container_node_ids = ["5-1641"]
default = true
access_token.keychain = true

[remotes.illustrations]
file_key = "Q5KZlwws4rsDW8grU91xLR"
container_node_ids = ["5-2"]
access_token.keychain = true


[profiles.illustrations]
extends = "android-webp"
remote = "illustrations"
densities = ["hdpi", "xhdpi", "xxhdpi", "xxxhdpi"]
night = "{base} (Dark)"

[profiles.icons]
extends = "compose"
remote = "icons"
color_mappings = [
    # Replace all colors because our icons are monochrome
    # just because we can
    { from = "*", to = "Color.Black" },
]
# Access our icons via FigxDemoIcons.{IconName}
extension_target = "com.example.figxdemo.ui.theme.FigxDemoIcons"
