[svg]
puzzle = "Environment / Puzzle"
first_aid = "Environment / First_Aid"
cupcake = "Environment / Cupcake"
sun = "Environment / Sun"
moon = "Environment / Moon"
rainbow = "Environment / Rainbow"
bulb = "Environment / Bulb"
cookie = "Environment / Cookie"
coffee_to_go = "Environment / Coffe_To_Go"
planet = "Environment / Planet"
water_drop = "Environment / Water_Drop"
coffee = "Environment / Coffee"
leaf = "Environment / Leaf"

users = "User / Users"
user_circle = "User / User_Circle"
user_card_id = "User / User_Card_ID"

compass = "Navigation / Compass"
globe = "Navigation / Globe"
house = "Navigation / House_03"
flag = "Navigation / Flag"
car_auto = "Navigation / Car_Auto"

settings = "Interface / Settings"
command = "Interface / Command"
heart = "Interface / Heart_02"
chart_bar = "Interface / Chart_Bar_Vertical_01"
trash = "Interface / Trash_Empty"
shopping_cart = "Interface / Shopping_Cart_01"
tag = "Interface / Tag"
main_component = "Interface / Main_Component"
switch_right = "Interface / Swicht_Right"
link = "Interface / Link_Horizontal"
star = "Interface / Star"
check_all = "Interface / Check_All_Big"
check = "Interface / Check"
