name: Unit-test Coverage

on:
  push:
    branches: [ master ]
    paths: [ 'crates/**', '.tarpaulin.toml' ]

jobs:
  test:
    name: Unit-test Coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    container:
      image: xd009642/tarpaulin:0.32.8
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo tarpaulin --config .tarpaulin.toml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tonykolomeytsev/figx
