on:
  push:
    tags:
      - "v*" # Run when tag matches v*, i.e. v1.0, v20.15.10
    branches:
      - "ci-*"

name: Release

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: aarch64-apple-darwin
          args: "--locked --release"
          toolchain: stable
          strip: true
      - uses: actions/upload-artifact@v4
        with:
          name: release-binary (macos)
          path: target/aarch64-apple-darwin/release/figx

  build-linux-gnu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          args: "--locked --release"
          toolchain: stable
          strip: true
      - uses: actions/upload-artifact@v4
        with:
          name: release-binary (linux-gnu)
          path: target/x86_64-unknown-linux-gnu/release/figx

  build-linux-musl:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-unknown-linux-musl
          args: "--locked --release"
          toolchain: stable
          strip: true
      - uses: actions/upload-artifact@v4
        with:
          name: release-binary (linux-musl)
          path: target/x86_64-unknown-linux-musl/release/figx

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-wix
          version: "0.3.9"
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          working-directory: ./app
          command: wix
          target: x86_64-pc-windows-msvc
          args: "-p figx --nocapture"
          toolchain: stable
          strip: false
      - uses: actions/upload-artifact@v4
        with:
          name: release-binary (windows)
          path: target/**/figx-*.msi

  publish-artifacts:
    name: "Publish Artifacts"
    needs:
      - build-macos
      - build-linux-gnu
      - build-linux-musl
      - build-windows
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Load Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./target

      - name: Collecting artifacts
        run: |
          set -euo pipefail
          tree -L 3 ./target

          echo "Packaging Windows MSI to figx-windows-x86_64.zip"
          cp "./target/release-binary (windows)/wix/"figx-*.msi ./figx-installer.msi
          zip -j figx-windows-x86_64.zip ./figx-installer.msi

          echo "Packaging Linux GNU binary to figx-linux-gnu-x86_64.tar.gz"
          tar -czf figx-linux-gnu-x86_64.tar.gz -C "./target/release-binary (linux-gnu)" figx

          echo "Packaging Linux MUSL binary to figx-linux-musl-x86_64.tar.gz"
          tar -czf figx-linux-musl-x86_64.tar.gz -C "./target/release-binary (linux-musl)" figx

          echo "Packaging macOS ARM64 binary to figx-macos-arm64.tar.gz"
          tar -czf figx-macos-arm64.tar.gz -C "./target/release-binary (macos)" figx

          echo "Final workspace contents:"
          ls -lh

      - uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            figx-windows-x86_64.zip
            figx-linux-gnu-x86_64.tar.gz
            figx-linux-musl-x86_64.tar.gz
            figx-macos-arm64.tar.gz
